_wandb:
    value:
        cli_version: 0.23.1
        e:
            6iqms0thr5penfnwdir9suzse3ve6jkk:
                email: shaanpatel98@gmail.com
                executable: /Users/shaanpatel/Desktop/AuroraNet/aurora-env/bin/python3
                git:
                    commit: 17361ea8ef0bc65ff4fda288f13399d7ef7bcb36
                    remote: git@github.com:shaandpatel/AuroraNet.git
                host: Shaans-MacBook-Pro.local
                os: macOS-15.3.1-arm64-arm-64bit
                program: -m src.models.train
                python: CPython 3.9.6
                root: /Users/shaanpatel/Desktop/AuroraNet
                startedAt: "2025-12-09T17:02:33.917695Z"
                writerId: 6iqms0thr5penfnwdir9suzse3ve6jkk
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.9.6
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 64
data_path:
    value: datafiles/processed/training_data.npz
dropout:
    value: 0.1
epochs:
    value: 20
hidden_size:
    value: 64
lr:
    value: 0.001
model_path:
    value: models/kp_lstm.pth
num_layers:
    value: 2
project_name:
    value: aurora-forecast
scaler_path:
    value: models/scaler.pkl
seed:
    value: 42
val_split:
    value: 0.2
